### ISSUE TITLE
unable to config websocket

### ISSUE THREAD

**Issue by JackyTrad** [pbielicki/soapui-websocket-transport#2]
I tried to add WebSocket Transport Plugin for soapUI following: https://github.com/pbielicki/soapui-websocket-transport

Tried to use the demo: ws://echo.websocket.org, by entering it as a wsdl. But I got the error: Wed Dec 17 09:51:14 IST 2014:ERROR:Failed to load url [file:/C:/Program%20Files%20(x86)/SmartBear/soapUI-Pro-4.5.1/bin/ws:/echo.websocket.org]

How I need to send the soap message ? It's look like the soapui is trying to find the wsdl in the local computer...

**Comment by pbielicki** [comment]
There is no WSDL for websocket service.
Try to use any random WSDL e.g. http://www.webservicex.net/globalweather.asmx?WSDL, choose any service, any sample request, change it (optionally) and replace target URL in SoapUI with ws://

Also, AFAIK websocket.org is a client demo - you need to develop a server. Try my simple example: https://github.com/pbielicki/soap-websocket-cxf/tree/master/soap-websocket-webapp

**Comment by JackyTrad** [comment]
Thanks for you quick response.
But I still did not understand how to config the websocket.
First, I did not understand why I can't use the socket of websocket.org, in there demo client, they are using the location ws://echo.websocket.org as a websocket and so do I... 
Second, I tried to replace the target URL as you explained, but I believes that i didn't do it right.
I added the WSDL you suggested, and got GlobalWeatherSoap with two requests. Went to the first one GetCitiesByCountry, and changed the url to ws://echo.websocket.org.and got the error : 

Tue Jan 06 16:17:03 IST 2015:ERROR:com.eviware.soapui.model.iface.Request$SubmitException: com.eviware.soapui.impl.wsdl.submit.RequestTransportRegistry$MissingTransportException: Missing protocol in endpoint [ws:/echo.websocket.org]
   com.eviware.soapui.model.iface.Request$SubmitException: com.eviware.soapui.impl.wsdl.submit.RequestTransportRegistry$MissingTransportException: Missing protocol in endpoint [ws:/echo.websocket.org]
    at com.eviware.soapui.impl.wsdl.WsdlRequest.submit(WsdlRequest.java:220)
    at com.eviware.soapui.impl.wsdl.panels.request.AbstractWsdlRequestDesktopPanel.doSubmit(AbstractWsdlRequestDesktopPanel.java:139)
    at com.eviware.soapui.impl.support.panels.AbstractHttpRequestDesktopPanel.onSubmit(AbstractHttpRequestDesktopPanel.java:817)
    at com.eviware.soapui.impl.support.panels.AbstractHttpRequestDesktopPanel$SubmitAction.actionPerformed(AbstractHttpRequestDesktopPanel.java:572)
    at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
    at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
    at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
    at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
    at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
    at java.awt.Component.processMouseEvent(Unknown Source)
    at javax.swing.JComponent.processMouseEvent(Unknown Source)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$200(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

Do I missing something ?
Thanks a lot

**Comment by pbielicki** [comment]
are you sure you put ws://echo... (double slash) instead of ws:/echo...?

**Comment by JackyTrad** [comment]
tested again and got from SoapUI Log:
Tue Jan 06 17:10:51 IST 2015:ERROR:Exception in request: javax.websocket.DeploymentException: The HTTP request to initiate the WebSocket connection failed
Tue Jan 06 17:10:51 IST 2015:ERROR:An error occurred [The HTTP request to initiate the WebSocket connection failed], see error log for details
Tue Jan 06 17:10:51 IST 2015:INFO:Error getting response for [GlobalWeatherSoap.GetCitiesByCountry:Request 1]; javax.websocket.DeploymentException: The HTTP request to initiate the WebSocket connection failed

and error log : 
Tue Jan 06 17:10:51 IST 2015:ERROR:javax.websocket.DeploymentException: The HTTP request to initiate the WebSocket connection failed
   javax.websocket.DeploymentException: The HTTP request to initiate the WebSocket connection failed
    at org.apache.tomcat.websocket.WsWebSocketContainer.connectToServer(WsWebSocketContainer.java:351)
    at org.apache.tomcat.websocket.WsWebSocketContainer.connectToServer(WsWebSocketContainer.java:198)
    at com.bielu.soapui.WebSocketRequestTransport.sendRequest(WebSocketRequestTransport.java:31)
    at com.eviware.soapui.impl.wsdl.WsdlSubmit.run(WsdlSubmit.java:119)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
   Caused by: java.io.EOFException
    at org.apache.tomcat.websocket.WsWebSocketContainer.processResponse(WsWebSocketContainer.java:580)
    at org.apache.tomcat.websocket.WsWebSocketContainer.connectToServer(WsWebSocketContainer.java:332)
    ... 8 more

**Comment by pbielicki** [comment]
yes, this is perfectly normal as the address you're targeting is not a valid websocket endpoint

**Comment by JackyTrad** [comment]
OK 
I will wait for the DEV team to finish there server endpoint and test it again.
I wanted to understand how to integrate the soapui with the websocket before i get the project for testing... 
Thanks a lot.
